### ISSUE TITLE
Error thrown during setting up smart reply

### ISSUE THREAD

**Issue by ibnclaudius** [vasani-arpit/WBOT#145]
**Describe the bug**

After login the app throw this error.
```
Looks like you got an error. Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'MutationObserver': pa.
    at __puppeteer_evaluation_script__:12:22
Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Nod.
    at __puppeteer_evaluation_script__:12:22
    at ExecutionContext.evaluateHandle (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/)
    at async setupSmartReply (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:171:9)
    at async Main (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:29:13)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/hel)
    at ExecutionContext.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/Execut)
    at ExecutionContext.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/hel)
    at DOMWorld.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/DOMWorld.js:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/helper.js:110:)
    at Page.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/Page.js:782:43)
    at Page.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/helper.js:111:2)
    at setupSmartReply (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:171:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Main (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:29:13)
Don't worry errors are good. They help us improve. A screenshot has already been saved as error.png in current director.

(node:1719) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'Muta.
    at __puppeteer_evaluation_script__:12:22
    at ExecutionContext.evaluateHandle (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/)
    at async setupSmartReply (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:171:9)
    at async Main (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:29:13)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/hel)
    at ExecutionContext.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/Execut)
    at ExecutionContext.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/hel)
    at DOMWorld.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/DOMWorld.js:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/helper.js:110:)
    at Page.evaluate (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/Page.js:782:43)
    at Page.<anonymous> (/Users/ibnclaudius/Development/ziben-labs/WBOT/node_modules/puppeteer-core/lib/helper.js:111:2)
    at setupSmartReply (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:171:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Main (/Users/ibnclaudius/Development/ziben-labs/WBOT/src/index.js:29:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins)
(node:1719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection.
```

**To Reproduce**

1. Clone the repo
2. Run the app
3. Login

**Expected behavior**

No errors during start up;

**Screenshots**

<img width="858" alt="Screen Shot 2020-06-07 at 20 09 28" src="https://user-images.githubusercontent.com/6260071/83982193-03122580-a8fb-11ea-84f4-aa4fb28193f8.png">

**App information (please complete the following information):**
 - Version 0.12.8
 - OS: macOS Catalina 10.15.5
 - NodeJS: 14.4.0

**Comment by marcosxp** [comment]
Mine started giving this error last week, any solution?

**Comment by vasani-arpit** [comment]
Smart replies are disabled for now. New release has been made.  Please update to latest version.
