### ISSUE TITLE
Suggestions configured not show - Mac OS

### ISSUE THREAD

**Issue by marcelloinfoweb** [vasani-arpit/WBOT#146]
**Describe the bug**
Does not show the suggestions configured in the bot.json to send.

**Screenshots**
![Captura de Tela 2020-06-09 às 12 56 09](https://user-images.githubusercontent.com/2093128/84171384-20f19e80-aa51-11ea-8f8e-7c38a6dc91c0.png)
![Captura de Tela 2020-06-09 às 12 56 47](https://user-images.githubusercontent.com/2093128/84171396-2353f880-aa51-11ea-8d00-e28a6951063a.png)

**App information (please complete the following information):**
 - Version 9.14
 - OS: macOS Catalina 10.15.2]

**Comment by marcelloinfoweb** [comment]
I realize you're not adding the div, when do you think you'll get an update?

It's not fair to offer a great feature without at least testing on other platforms and still put it to use.

Looking forward to an upgrade, thanks for your great service!

**Comment by pavanmehta91** [comment]
@marcelloinfoweb Since it's a free open source project everybody is invited to contribute. @vasani-arpit Arpit does not own a mac so he can't test on a mac. Hope you understand thanks.

**Comment by marcelloinfoweb** [comment]
I fully understand and appreciate the invitation to contribute, but it is unwise to offer a system without testing.  I would at least post a warning about problems with that version on other systems.

**Comment by pavanmehta91** [comment]
Only if the guy had Mac to test. So it's not unwise imo. 
He's not providing any commercial services so it's unwise to expect everything would work as it's and not break. It's only wise to create PRs, contribute and report issues when necessary. But expecting perfection for an unpaid work is defnitely unwise.

**Comment by marcelloinfoweb** [comment]
"... is unwise to offer a system without testing ..."

**Comment by marcelloinfoweb** [comment]
**LOG** 
Running from source package

------------------
Looks like you got an error. Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node.
    at __puppeteer_evaluation_script__:12:22
Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at __puppeteer_evaluation_script__:12:22
    at ExecutionContext._evaluateInternal (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/ExecutionContext.js:81:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/helper.js:111:15)
    at DOMWorld.evaluate (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.evaluate (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/Page.js:833:43)
    at Page.<anonymous> (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/helper.js:112:23)
    at setupSmartReply (/home/msc/Downloads/WBOT/src/index.js:171:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
Don't worry errors are good. They help us improve. A screenshot has already been saved as error.png in current directory. Please mail it on vasani.ar.

(node:2939) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is .
    at __puppeteer_evaluation_script__:12:22
    at ExecutionContext._evaluateInternal (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/ExecutionContext.js:81:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/helper.js:111:15)
    at DOMWorld.evaluate (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.evaluate (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/Page.js:833:43)
    at Page.<anonymous> (/home/msc/Downloads/WBOT/node_modules/puppeteer-core/lib/helper.js:112:23)
    at setupSmartReply (/home/msc/Downloads/WBOT/src/index.js:171:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:2939) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function witho)
(node:2939) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will te.

**Comment by vasani-arpit** [comment]
We have solved the last one by disabling quick-reply feature in latest release v0.12.8

**Comment by marcelloinfoweb** [comment]
I would like to use the suggestions.

**Comment by vasani-arpit** [comment]
I am working on a solution as this is my side project, I can't allocate much time to this.
