### ISSUE TITLE
'TimeoutError'

### ISSUE THREAD

**Issue by marcosxp** [vasani-arpit/WBOT#150]
My system has been showing the following error for some time, what can it be?

{ TimeoutError: waiting for selector ".app" failed: timeout 30000ms exceeded
    at new WaitTask (C:\snapshot\workspace\node_modules\puppeteer-core\lib\DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (C:\snapshot\workspace\node_modules\puppeteer-core\lib\DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (C:\snapshot\workspace\node_modules\puppeteer-core\lib\DOMWorld.js:444:17)
    at Frame.waitForSelector (C:\snapshot\workspace\node_modules\puppeteer-core\lib\FrameManager.js:628:47)
    at Frame.<anonymous> (C:\snapshot\workspace\node_modules\puppeteer-core\lib\helper.js:111:23)
    at Page.waitForSelector (C:\snapshot\workspace\node_modules\puppeteer-core\lib\Page.js:1046:29)
    at setupSmartReply (C:\snapshot\workspace\src\index.js:0:0)
    at Main (C:\snapshot\workspace\src\index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

**Comment by prakhargurunani** [comment]
Closing as https://github.com/kazakbala/WBOT/pull/1 is merged.
