### ISSUE TITLE
WBOT can't start

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#298]
Looks like you got an error. TimeoutError: waiting for selector "img[alt='Scan me!'], canvas" failed: timeout 30000ms exceeded
{ TimeoutError: waiting for selector "img[alt='Scan me!'], canvas" failed: timeout 30000ms exceeded
    at new WaitTask (/snapshot/workspace/node_modules/puppeteer-core/lib/DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (/snapshot/workspace/node_modules/puppeteer-core/lib/DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (/snapshot/workspace/node_modules/puppeteer-core/lib/DOMWorld.js:444:17)
    at Frame.waitForSelector (/snapshot/workspace/node_modules/puppeteer-core/lib/FrameManager.js:628:47)
    at Frame.<anonymous> (/snapshot/workspace/node_modules/puppeteer-core/lib/helper.js:111:23)
    at Page.waitForSelector (/snapshot/workspace/node_modules/puppeteer-core/lib/Page.js:1046:29)
    at getAndShowQR (/snapshot/workspace/src/index.js:0:0)
    at Main (/snapshot/workspace/src/index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

**Comment by vasani-arpit** [comment]
This is an issue due to multi-device beta. Delete chromium-data folder and remove the device from phone. Then try to Link new device. It should work.

**Comment by tradename** [comment]
Worked. Thank you... but seems you have to do that every time you start the Bot as the error pop ups every-time you start WBOT

**Comment by vasani-arpit** [comment]
As MD support is in Beta WA logs you out automatically after few hours. That's why this happens.

**Comment by tradename** [comment]
ooh i understand. and thanks for this

**Comment by AngelJRomero21** [comment]
Hay forma de que cada vez que inicie el bot no tenga que escanear el codigo?

**Comment by vrushalipachchigar** [comment]
@AngelJRomero21 As of now this feature isn't provided for multi device login. WBOT saves data for one device log in so you don't have to scan QR every time you open WBOT
