### ISSUE TITLE
Page Crashing. After 20 minutes of running

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#315]
Error: Page crashed!
    at Page._onTargetCrashed (/home/carol/WBOT/node_modules/puppeteer-core/lib/Page.js:170:24)
    at CDPSession.Page.client.on.event (/home/carol/WBOT/node_modules/puppeteer-core/lib/Page.js:125:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/home/carol/WBOT/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/home/carol/WBOT/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/home/carol/WBOT/node_modules/puppeteer-core/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/home/carol/WBOT/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/carol/WBOT/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
- Downloading chrome

**Comment by vasani-arpit** [comment]
are you running this in headless mode?
are you using any scripts in `CustomInjectionFolder` config?

**Comment by tradename** [comment]
yes its in headless mode. Ubuntu Digitalocean VPS. It runs for a few minutes but after about 15min it crashes

**Comment by vasani-arpit** [comment]
as puppeteer is based on chromium it is resource heavy. Make sure you have at least 1.5-2 gigs of ram to run it smoothly.

**Comment by tradename** [comment]
Increasing RAM resolved the issue. Thanks
