### ISSUE TITLE
WBOT-Linux to Raspberry PI ARM

### ISSUE THREAD

**Issue by chalfling** [vasani-arpit/WBOT#354]
**Is your feature request related to a problem? Please describe.**
I've tried to build and run on my raspberry pi 3, but got some errors.

**Describe the solution you'd like**
Release a ARM version.

**Comment by vasani-arpit** [comment]
Haven't worked with ARM before. How can I test it?

**Comment by lucasvmx** [comment]
> Haven't worked with ARM before. How can I test it?

You can test it by running WBot inside a docker container. https://github.com/lukechilds/dockerpi

**Comment by lucasvmx** [comment]
> **Is your feature request related to a problem? Please describe.** I've tried to build and run on my raspberry pi 3, but got some errors.
> 
> **Describe the solution you'd like** Release a ARM version.

1) What's your nodeJS version? `node --version`
2) What commands did you run?
3) What's your raspbian version? `cat /etc/os-release`

**Comment by chalfling** [comment]
> > **Is your feature request related to a problem? Please describe.** I've tried to build and run on my raspberry pi 3, but got some errors.
> > **Describe the solution you'd like** Release a ARM version.
> 
> 1. What's your nodeJS version? `node --version`
v12.22.9
> 2. What commands did you run?
node src/index.js
> 3. What's your raspbian version? `cat /etc/os-release`
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

**Comment by chalfling** [comment]
> `npm run start`

npm run start



> wbot@0.43.0 start
> node src/index.js

/home/ubuntu/WBOT/src/index.js:396
    const data = msg?.body;
                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by lucasvmx** [comment]
> > > **Is your feature request related to a problem? Please describe.** I've tried to build and run on my raspberry pi 3, but got some errors.
> > > **Describe the solution you'd like** Release a ARM version.
> > 
> > 
> > 
> > 1. What's your nodeJS version? `node --version`
> >    v12.22.9
> > 2. What commands did you run?
> >    node src/index.js
> > 3. What's your raspbian version? `cat /etc/os-release`
> >    PRETTY_NAME="Ubuntu 22.04.2 LTS"
> >    NAME="Ubuntu"
> >    VERSION_ID="22.04"
> >    VERSION="22.04.2 LTS (Jammy Jellyfish)"
> >    VERSION_CODENAME=jammy
> >    ID=ubuntu
> >    ID_LIKE=debian
> >    HOME_URL="https://www.ubuntu.com/"
> >    SUPPORT_URL="https://help.ubuntu.com/"
> >    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> >    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

Maybe WBOT is just unable to be executed correctly with nodeJS 12.x. Try upgrading your node version to at least the maitanance LTS version (16.x). After doing that, try running WBOT again and tell us
