### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by webhype** [vasani-arpit/WBOT#366]
**Describe the bug**

██╗    ██╗██████╗  ██████╗ ████████╗
██║    ██║██╔══██╗██╔═══██╗╚══██╔══╝
██║ █╗ ██║██████╔╝██║   ██║   ██║
██║███╗██║██╔══██╗██║   ██║   ██║
╚███╔███╔╝██████╔╝╚██████╔╝   ██║
 ╚══╝╚══╝ ╚═════╝  ╚═════╝    ╚═╝

v0.56.0
✔ Downloading chromium ... done!
⣻ Launching browser
/var/mm/WBOT/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/var/mm/WBOT/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /var/mm/WBOT/node_modules/whatsapp-web.js/src/Client.js:728:36
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.12.0

**To Reproduce**
1. cloned github
2. `./setup/setup.sh`
3. `xvfb-run node src/index.js`

**Expected behavior**
That it start without errors. Honestly not sure what to expect because the `readme.md` doesn't show or what comes next 🙂

It's also completely unclear to me how this bot will "log into" my WhatsApp. I assume it launches Chromium and shows the WhatsApp QR code at some point. But what if I run this from a Linux computer that has graphical user interface (like the droplets that you suggested)? This part is not explained at all.

**App information (please complete the following information):**
 - Version: latest (downloaded today)
 - OS: Ubuntu 22.04 with all updates and upgrades
 
**Additional context**
N/A

**Comment by vasani-arpit** [comment]
Resolved in latest version. https://github.com/vasani-arpit/WBOT/releases
