### ISSUE TITLE
New Bug: First Start > Console "Bug"

### ISSUE THREAD

**Issue by oOHiyoriOo** [vasani-arpit/WBOT#59]
Just Started the executable on my Ubuntu 18.04 server and got following:

```bash
⣷ Downloading chrome
(node:6995) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'branch_base_position' of undefined
    at getRevNumber.fetch.then.then.json (/snapshot/WBOT/src/detectRev.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections⣟ Downloading chrome
```
idk if it stopped working, but iam going to wait for a while if it continues.

**Comment by oOHiyoriOo** [comment]
figured out i fcuked up not u... sry
