### ISSUE TITLE
latest release is not working

### ISSUE THREAD

**Issue by Hexenon** [vasani-arpit/WBOT#85]
**Describe the bug**

**To Reproduce**
1. Go to 'open the app'
2. Click on 'nowhere'
3. Scroll down to 'wait until: '

√ Downloading chrome ... done!
√ Launching Chrome ... done!
√ Opening Whatsapp ... done!
i You are not logged in. Please scan the QR below
Looks like you got an error.TimeoutError: waiting for selector "img[alt='Scan me!']" failed: timeout 30000ms exceeded
{ TimeoutError: waiting for selector "img[alt='Scan me!']" failed: timeout 30000ms exceeded
    at new WaitTask (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\DOMWorld.js:444:17)
    at Frame.waitForSelector (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\FrameManager.js:628:47)
    at Frame.<anonymous> (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\helper.js:111:23)
    at Page.waitForSelector (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\Page.js:1046:29)
    at getAndShowQR (F:\snapshot\WBOT\src\index.js:0:0)
    at Main (F:\snapshot\WBOT\src\index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
Don't worry errors are good. They help us improve. A screenshot has already been saved as error.png in current directory. Please mail it on vasani.arpit@gmail.com along with the steps to reproduce it.
(node:12120) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "img[alt='Scan me!']" failed: timeout 30000ms exceeded
    at new WaitTask (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\DOMWorld.js:444:17)
    at Frame.waitForSelector (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\FrameManager.js:628:47)
    at Frame.<anonymous> (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\helper.js:111:23)
    at Page.waitForSelector (F:\snapshot\WBOT\node_modules\puppeteer-core\lib\Page.js:1046:29)
    at getAndShowQR (F:\snapshot\WBOT\src\index.js:0:0)
    at Main (F:\snapshot\WBOT\src\index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]
 - additional info which might be useful to reproduce the issue

**Additional context**

**Comment by vasani-arpit** [comment]
@Hexenon Which OS you are running on?

**Comment by Hexenon** [comment]
windows 10 pro, seems like the qr component is not anymore the same. I inspected the component

**Comment by panteLx** [comment]
same issue for me with win 10

**Comment by vasani-arpit** [comment]
I will soon make a release but the solution is to change the selector becuase WA changed img tag to canvas so current selector will not work 

change

`img[alt='Scan me!']` on line [143](https://github.com/vasani-arpit/WBOT/blob/master/src/index.js#L143) and 144 in [index.js](https://github.com/vasani-arpit/WBOT/blob/master/src/index.js)

to

`canvas[role='img']`

**Comment by panteLx** [comment]
if you want you can accept my pull request ;)

**Comment by vasani-arpit** [comment]
@panteLx Thanks, will do.

**Comment by panteLx** [comment]
@vasani-arpit how can i build the app on windows? tried `npm run pack` but its not working cause "pkg" cant be found.

**Comment by vasani-arpit** [comment]
Please do `npm install` to download all the required dependencies

**Comment by Hexenon** [comment]
@panteLx you need to `npm i -g pkg` then you can access to it globally.

**Comment by Hexenon** [comment]
@vasani-arpit i will contribute adding some webhooks functionality and security, stay tuned ill send you some PR in the future
